server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:q123q123@tcp(127.0.0.1:3306)/gozero?parseTime=True
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s